@appJson = application/json
@apiVersion = v2
@controllerAddress = {{baseAddress}}/restuarant/{{apiVersion}}


GET {{controllerAddress}}
### GET - Get All Restuarants


POST {{controllerAddress}}/find
Accept: {{appJson}}
Content-Type: {{appJson}}

{
  "name": "Test",
  "cuisine": "Test"
}
### POST - Find Restuarants by search criteria


@id = 66b7b0838f24edd1352693b4
GET {{controllerAddress}}/{{id}}
### GET - Get Restuarant by id



POST {{baseAddress}}/restuarant/{{apiVersion}}
Accept: {{appJson}}
Content-Type: {{appJson}}

{
    "name": "Test",
    "cuisineType": "Test",
    "website": "https://www.google.com/",
    "phone": "1112223333",
    "address": {
        "street": "123 Test Street",
        "city": "Somewhere",
        "state": "KY",
        "zipCode": "12345",
        "country": "United States"
    }
}
### POST - Add a new Restuarant



PUT {{baseAddress}}/restuarant/{{apiVersion}}
Accept: {{appJson}}
Content-Type: {{appJson}}

{
    "id": "66b03c2009119f72a45f9c4f",
    "name": "Test",
    "cuisineType": "Test",
    "website": "https://www.google.com",
    "phone": "1112223333",
    "address": {
        "street": "123 Test Street",
        "city": "Somewhere",
        "state": "KY",
        "zipCode": "12345",
        "country": "United States"
    }
}
### PUT - Update an existing Restuarant